### ISSUE TITLE
Question about the antenna

### ISSUE THREAD

**Issue by troublew** [SolidHal/AsusC201-usb-wifi-from-webcam#1]
Hello, thanks for your tutorial.
I have a question about the antenna; aren't the antennas the white cable and the black cable? (maybe it's connected to the bluetooth soldered card).
I want to install this usb key into the laptop (that's some ebay atheros wifi key, don't have much money to pay for the 44$ thinkpenguin wifi key):
![pic](https://user-images.githubusercontent.com/19409956/60531305-f9e80400-9cfa-11e9-9f76-92290ae19db2.jpg)
Would I be able to disconnect the white and black cable, and connect one of the two to this wifi key without using the silver cable?
Thanks!

**Comment by SolidEva** [comment]
Yep, the antenna cables are the white and black cables in the c201. If the antenna connector is the same size on that atheros usb wifi device then you will be able to easily swap that grey antenna cable for the white or black one. 

If you end up getting it and finding room inside the laptop for it I'd really appreciate some pictures if you have the chance! :)
The cheaper price and antenna connector is very compelling for those interested in installing it into the laptop.

**Comment by troublew** [comment]
Thanks you. I'll buy it and try.
